---
- name: install prerequisites
  become: yes
  apt: pkg={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - apt-transport-https 
    - ca-certificates

- name: install repository key
  become: yes
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: install repository
  become: yes
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

- name: install required software
  become: yes
  apt: pkg=docker-engine state=latest update_cache=true cache_valid_time=3600
  register: status
  notify: start docker

- name: docker run --rm hello-world
  become: yes
  register: out
  shell: docker run --rm hello-world
  when: status | changed

- debug: var=out.stdout_lines
  when: status | changed
